export const DBF2SQL_MAPPING_LIST_REQUEST = 'DBF2SQL_MAPPING_LIST_REQUEST';
export const DBF2SQL_MAPPING_LIST_SUCCESS = 'DBF2SQL_MAPPING_LIST_SUCCESS';
export const DBF2SQL_MAPPING_LIST_FAIL = 'DBF2SQL_MAPPING_LIST_FAIL';

export const DBF2SQL_MAPPING_DETAIL_REQUEST = 'DBF2SQL_MAPPING_DETAIL_REQUEST';
export const DBF2SQL_MAPPING_DETAIL_SUCCESS = 'DBF2SQL_MAPPING_DETAIL_SUCCESS';
export const DBF2SQL_MAPPING_DETAIL_FAIL = 'DBF2SQL_MAPPING_DETAIL_FAIL';

export const DBF2SQL_MAPPING_CREATE_REQUEST = 'DBF2SQL_MAPPING_CREATE_REQUEST';
export const DBF2SQL_MAPPING_CREATE_SUCCESS = 'DBF2SQL_MAPPING_CREATE_SUCCESS';
export const DBF2SQL_MAPPING_CREATE_FAIL = 'DBF2SQL_MAPPING_CREATE_FAIL';