export const DBF2SQL_MAPPING_LIST_REQUEST = 'DBF2SQL_MAPPING_LIST_REQUEST';
export const DBF2SQL_MAPPING_LIST_SUCCESS = 'DBF2SQL_MAPPING_LIST_SUCCESS';
export const DBF2SQL_MAPPING_LIST_FAIL = 'DBF2SQL_MAPPING_LIST_FAIL';

export const DBF2SQL_MAPPING_DETAIL_REQUEST = 'DBF2SQL_MAPPING_DETAIL_REQUEST';
export const DBF2SQL_MAPPING_DETAIL_SUCCESS = 'DBF2SQL_MAPPING_DETAIL_SUCCESS';
export const DBF2SQL_MAPPING_DETAIL_FAIL = 'DBF2SQL_MAPPING_DETAIL_FAIL';
export const DBF2SQL_MAPPING_DETAIL_RESET = 'DBF2SQL_MAPPING_DETAIL_RESET';

export const DBF2SQL_MAPPING_CREATE_REQUEST = 'DBF2SQL_MAPPING_CREATE_REQUEST';
export const DBF2SQL_MAPPING_CREATE_SUCCESS = 'DBF2SQL_MAPPING_CREATE_SUCCESS';
export const DBF2SQL_MAPPING_CREATE_FAIL = 'DBF2SQL_MAPPING_CREATE_FAIL';
export const DBF2SQL_MAPPING_CREATE_RESET = 'DBF2SQL_MAPPING_CREATE_RESET';

export const DBF2SQL_MAPPING_EDIT_REQUEST = 'DBF2SQL_MAPPING_EDIT_REQUEST';
export const DBF2SQL_MAPPING_EDIT_SUCCESS = 'DBF2SQL_MAPPING_EDIT_SUCCESS';
export const DBF2SQL_MAPPING_EDIT_FAIL = 'DBF2SQL_MAPPING_EDIT_FAIL';
export const DBF2SQL_MAPPING_EDIT_RESET = 'DBF2SQL_MAPPING_EDIT_RESET';

export const DBF2SQL_MAPPING_DELETE_REQUEST = 'DBF2SQL_MAPPING_DELETE_REQUEST';
export const DBF2SQL_MAPPING_DELETE_SUCCESS = 'DBF2SQL_MAPPING_DELETE_SUCCESS';
export const DBF2SQL_MAPPING_DELETE_FAIL = 'DBF2SQL_MAPPING_DELETE_FAIL';
export const DBF2SQL_MAPPING_DELETE_RESET = 'DBF2SQL_MAPPING_DELETE_RESET';